[project]
name = 'Healthcare-Data-Management-System'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.access-control]
path = 'contracts/access-control.clar'
clarity_version = 2
epoch = 2.5

[contracts.audit-trail]
path = 'contracts/audit-trail.clar'
clarity_version = 2
epoch = 2.5

[contracts.medical-certification-nfts]
path = 'contracts/medical-certification-nfts.clar'
clarity_version = 2
epoch = 2.5

[contracts.medical-record-management]
path = 'contracts/medical-record-management.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
